export const REGISTER_NEW_USER_REQUEST = 'REGISTER_NEW_USER_REQUEST'
export const REGISTER_NEW_USER_SUCCESS ='REGISTER_NEW_USER_SUCCESS '
export const REGISTER_NEW_USER_FAILURE ='REGISTER_NEW_USER_FAILURE'


export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS'
export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE'


export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'


export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'


export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE'


export const REMOVE_TO_CART_SUCCESS = 'REMOVE_TO_CART_SUCCESS'
export const REMOVE_TO_CART_FAILURE = 'REMOVE_TO_CART_FAILURE'

export const INCREMENT_QTY = 'INCREMENT_QTY'
export const DECREMENT_QTY = 'DECREMENT_QTY'
